### ISSUE TITLE
Samo jedna matematska operacija dozvolljena

### ISSUE THREAD

**Issue by AlemZolota** [ekorem1988/Calculator#4]
![image](https://user-images.githubusercontent.com/25816995/159910515-e77dda19-3719-4f1a-824f-999f35379fc6.png)

**Comment by ekorem1988** [comment]
znam, to sam uradio da moze i drugi broj bit negativan im jos togza sredit

**Comment by AlemZolota** [comment]
Jesi li ovo fixo?
