### ISSUE TITLE
Definisati odgovarajuci scope za variable unutar komponente

### ISSUE THREAD

**Issue by AlemZolota** [ekorem1988/Calculator#8]
Trenutno sve variable unutar komponente su definisane kao public. 
Dodjeli variablama odgovrajuci scope. Isto za variable unutar metoda koje su definisane kao var to zamjeniti sa const ili let.

**Comment by ekorem1988** [comment]
pa kolko vidim nisam nigdje koristio var, ove variable sto koristim u metodama su ustavri ove gore prve pocetne i njih koristim sa ovim "this" ispred,  a ako nisu public ond ih ne mogu korisdtit na tamplate

**Comment by AlemZolota** [comment]
Ok, ja sam onda gledao u stariju verziju koda. 
Onda za te variable na vrhu klase definisi scope. 

listOfoNumbers = [7,8,9,4,5,6,1,2,3,0];
calcRezult = 0;
inputField = "";
mathOper = MathOper;
